### ISSUE TITLE
[Dockerfile-dcrd] use DCR_RELEASE v1.2.0

### ISSUE THREAD

**Issue by pricejn2** [decred/dcrdocker#30]
Mind updating the published Dockerfile-dcrd to use latest release v1.2.0? Thanks!

https://github.com/decred/dcrdocker/blob/master/Dockerfile-dcrd#L11

**Comment by chappjc** [comment]
It seems to have been updated in https://github.com/decred/dcrdocker/pull/33, although it would seem to need an update for 1.3.0 now.

**Comment by pricejn2** [comment]
@chappjc indeed, thanks for the heads up. closing.
